### PR TITLE
[INV-3928] Fix time interval between heartbeats

### LINKED ISSUE #3928: Mobile: When out of service, cached recordsets won't display unless app is set to offline mode
This stumped me for a minute when I was field testing so I guarantee it will stump some users. Should there be a message pop-up telling the user to toggle to offline to display cached records on map? Discuss.

### PR DESCRIPTION
**Pull request by LocalNewsTV**
# Overview

This PR includes the following proposed change(s):

- Fix issue where time was not being reduced properly between failed heartbeats causing each check to last a full minute or longer,
- Heartbeats now go 60 seconds per beat, or 20 seconds per beat if there is a currently failing beat on the number (original intention)

- If attempting to fetch table rows from a recordset but the user has spotty internet, attempt to grab records from the cache (if exists).

Possible Fix for #3928, pending additional details

### CODE REVIEW

File: app/src/state/sagas/map/dataAccess.ts [hunk 1]
```diff
@@ -261,25 +261,34 @@ export function* handle_ACTIVITIES_TABLE_GET_ROWS(action) {
...
+      Activity.getRowsSuccess({
+        recordSetID: recordSetID,
+        rows: records,
+        tableFiltersHash: tableFiltersHash,
+        page: page,
+        limit: limit
+      })
+    );
+  } catch {
+    // do nothing. An expected error here is 'repository n not found' if the recordset contains no cache.
```
Comment (meghna0593) [inline app/src/state/sagas/map/dataAccess.ts]: Consider adding a log statement here instead of leaving the catch block empty. Using `console.error(e)` would help capture unexpected errors and make debugging easier.

Comment (LocalNewsTV) [reply app/src/state/sagas/map/dataAccess.ts]: @meghna0593  Fair, better to have and not need than need and not have.

Comment (meghna0593) [reply app/src/state/sagas/map/dataAccess.ts]: ^ a quote worthy of being framed

**Comment by meghna0593** [comment]
Works well. Gets me back online when network is available. 

We should probably dispatch `AuthActions.makeOfflineUserCurrent` too?

File: app/src/state/sagas/network.ts [hunk 2]
```diff
@@ -31,10 +31,9 @@ const canConnectToNetwork = async (url: string): Promise<boolean> => {
 const getTimeBetweenTicks = (heartbeatFailures: number): number => {
   const BASE_SECONDS_BETWEEN_FAILURE = 20;
   const BASE_SECONDS_BETWEEN_SUCCESS = 60;
-  return Math.max(
-    BASE_SECONDS_BETWEEN_FAILURE * 1000 * Math.pow(1.1, heartbeatFailures),
-    BASE_SECONDS_BETWEEN_SUCCESS * 1000
-  );
+  return heartbeatFailures === 0
```
Comment (plasticviking) [inline app/src/state/sagas/network.ts]: This seems harder to intuitively understand than the previous implementation?

**Comment by LocalNewsTV** [comment]
@meghna0593 
There is no need. The exact same information was parsed from the users token when they logged in, making the `makeOfflineUserCurrent` call wouldn't change anything.

Please review the reducer case for `makeOfflineUserCurrent` and the function `loadCurrentStateFromIdToken`
