### PR TITLE
Fix crash when adding more than 4 custom recordsets

### LINKED ISSUE #4219: Mobile: Adding 4+ custom recordsets causes crash
I've had varying results after testing this issue a few times. The first time the app crashed on me it was after adding my 4th custom recordset. The next few times it was between 6 and 8 added recordsets. It seems like adding the recordsets causes a memory usage spike and eventually crashes the app. I don't think the app needs to handle 8 recordsets necessarily but 4 or 5 is probably a reasonable amount.

### PR DESCRIPTION
**Pull request by meghna0593**
# Overview

This PR includes the following proposed change(s):

- Fixes #4219 
- Tested on the browser, iPad and iPad simulator
- Noticed that the app is slow on initial load after creating 8+ recordsets.  [#4229](https://github.com/bcgov/invasivesbc/issues/4229)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

### CODE REVIEW

File: app/src/state/sagas/map.ts [hunk 1]
```diff
@@ -547,12 +547,12 @@ function* handle_MAP_INIT_FOR_RECORDSETS() {
...
   // current layers
-  const layers = yield select((state) => state.Map.layers);
+  const mapState = yield select(selectMap);
+  const layers = mapState.layers;
   const layerIDs = layers.map((layer) => layer.recordSetID);
 
-  // current but unintialized:
   const currentUninitializedLayers = layers
-    .filter((layer) => !layer.loading)
+    .filter((layer) => !Object.prototype.hasOwnProperty.call(layer, 'loading'))
```
Comment (LocalNewsTV) [inline app/src/state/sagas/map.ts:555]: is there a reason to use this prototype instead of ES2022 supported Object.hasOwn?

**Review by LocalNewsTV — DISMISSED** [review]
Solution corrects the regression previously introduced.

File: app/src/state/sagas/map.ts (hunk 1 above)
Comment (meghna0593) [reply app/src/state/sagas/map.ts:555]: No specific reason — either approach works. The one I used is the older, widely supported format (Object.prototype.hasOwnProperty.call). The method you suggested (Object.hasOwn) is recommended for modern environments.

Comment (plasticviking) [reply app/src/state/sagas/map.ts:555]: +1 for this. Also, I think this line is probably the only important one?

Comment (meghna0593) [reply app/src/state/sagas/map.ts:555]: Yes, looks like this is the only change needed to fix the crashes (lol). 

However, there's a noticeable slowdown on initial login when there are more than 8 custom recordsets. Layer toggling behaves inconsistently on page refresh — sometimes it works, sometimes it doesn't.
