### PR TITLE
Mobile: Activity button on Offline Sync Status Dialog box doesn't load activity

### LINKED ISSUE #3684: Mobile: Load activity button on offline sync status menu doesn't work
The floppy disk icon on the offline sync status menu does not take you to the activity when clicked.

### PR DESCRIPTION
**Pull request by meghna0593**
# Overview
Resolves the issue where the dialog box does not close when attempting to load offline activity.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

### CODE REVIEW

File: app/src/UI/OfflineDataSync/OfflineDataSyncTable.tsx [hunk 1]
```diff
@@ -63,8 +66,8 @@ export const OfflineDataSyncTable = () => {
                         disabled={!(workingOffline || authenticated)}
                         color="primary"
                         onClick={() => {
-                          dispatch(Activity.getLocal(key));
```
Comment (LocalNewsTV) [inline app/src/UI/OfflineDataSync/OfflineDataSyncTable.tsx:66]: Nice catch on the duplicate run of getLocal

**Review by LocalNewsTV — COMMENTED** [review]
I'm not sure if we can confidently call this enough to close the ticket.

One outlying issue is that we're not caching the API Docs (because they are massive) so if we start from an offline context we can't actually load the offline activities due to needing the apidocs.

If we don't have the apiDocs, the form page appears but it just says `loading` and will never terminate. A console log of Record.tsx l:63 
`if (activity_ID && apiDocsWithSelectOptions && apiDocsWithViewOptions && loading === false)` shows that both apiDoc options are null

We may just want to verify if the issue is that we're getting `loading` or if the issue was strictly navigating. On mobile users can't see the URL they're on :)

**Comment by meghna0593** [comment]
> I'm not sure if we can confidently call this enough to close the ticket.
> 
> One outlying issue is that we're not caching the API Docs (because they are massive) so if we start from an offline context we can't actually load the offline activities due to needing the apidocs.
> 
> If we don't have the apiDocs, the form page appears but it just says `loading` and will never terminate. A console log of Record.tsx l:63 `if (activity_ID && apiDocsWithSelectOptions && apiDocsWithViewOptions && loading === false)` shows that both apiDoc options are null
> 
> We may just want to verify if the issue is that we're getting `loading` or if the issue was strictly navigating. On mobile users can't see the URL they're on :)

Issue was just with navigating to activities on clicking the button and the dialog box persisting
